// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRfriPz9deJ-Ld3SWVxOqLSeH5oBS8-5E',
    appId: '1:725637636773:web:be1284bbd6073b791f234c',
    messagingSenderId: '725637636773',
    projectId: 'maily-bbc51',
    authDomain: 'maily-bbc51.firebaseapp.com',
    databaseURL: 'https://maily-bbc51-default-rtdb.firebaseio.com',
    storageBucket: 'maily-bbc51.appspot.com',
    measurementId: 'G-8V7RYMLTHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXVetjgEcP8m7H98zMBj95SD5XXp7h3S4',
    appId: '1:725637636773:android:0db3472660b692a31f234c',
    messagingSenderId: '725637636773',
    projectId: 'maily-bbc51',
    databaseURL: 'https://maily-bbc51-default-rtdb.firebaseio.com',
    storageBucket: 'maily-bbc51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApg0djZjNnV_YLKsWFcQV-Hb_TA-A1Xo0',
    appId: '1:725637636773:ios:b63fc2096e56bd821f234c',
    messagingSenderId: '725637636773',
    projectId: 'maily-bbc51',
    databaseURL: 'https://maily-bbc51-default-rtdb.firebaseio.com',
    storageBucket: 'maily-bbc51.appspot.com',
    androidClientId: '725637636773-1sd5k59pqkh1b5vv9rf4irs9e2c5m606.apps.googleusercontent.com',
    iosClientId: '725637636773-75epm9h8ts3pba4555s95pfptjdu3oh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.maily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApg0djZjNnV_YLKsWFcQV-Hb_TA-A1Xo0',
    appId: '1:725637636773:ios:b63fc2096e56bd821f234c',
    messagingSenderId: '725637636773',
    projectId: 'maily-bbc51',
    databaseURL: 'https://maily-bbc51-default-rtdb.firebaseio.com',
    storageBucket: 'maily-bbc51.appspot.com',
    androidClientId: '725637636773-1sd5k59pqkh1b5vv9rf4irs9e2c5m606.apps.googleusercontent.com',
    iosClientId: '725637636773-75epm9h8ts3pba4555s95pfptjdu3oh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.maily',
  );
}
